# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

IAM_stripe <- function(listInput, listSpec, listStochastic, listScen, RecType1, RecType2, RecType3, Scenarii, Bootstrp, nbBoot, GestInd, mOth, bounds, TAC, FBAR, othSpSup, effSup, GestParam, EcoDcf, persCalc, dr, SRind, listSR, TypeSR, mFM, TACbyF, Ftarg, W_Ftarg, MeanRec_Ftarg, parBHV, parQEX, tacCTRL, stochPrice, updateE, parOQD, bootVar = NULL, verbose = 0L) {
    .Call(`_IAM_IAM_stripe`, listInput, listSpec, listStochastic, listScen, RecType1, RecType2, RecType3, Scenarii, Bootstrp, nbBoot, GestInd, mOth, bounds, TAC, FBAR, othSpSup, effSup, GestParam, EcoDcf, persCalc, dr, SRind, listSR, TypeSR, mFM, TACbyF, Ftarg, W_Ftarg, MeanRec_Ftarg, parBHV, parQEX, tacCTRL, stochPrice, updateE, parOQD, bootVar, verbose)
}

